# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_hash', models.CharField(max_length=40)),
                ('last_seen', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=40)),
                ('nsfw', models.BooleanField(default=0)),
                ('thumbnail_hash', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=8, max_digits=8)),
                ('origin', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_fee', models.DecimalField(decimal_places=8, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=40)),
                ('last_seen', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('nsfw', models.BooleanField(default=0)),
                ('avatar_hash', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('snapchat', models.CharField(max_length=100)),
                ('pgp_key', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('encryption_key', models.CharField(max_length=100)),
                ('header_hash', models.CharField(max_length=40)),
                ('text_color', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=100)),
                ('secondary_color', models.CharField(max_length=100)),
                ('background_color', models.CharField(max_length=100)),
                ('is_vendor', models.BooleanField(default=0)),
                ('is_moderator', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=0)),
                ('tags', models.CharField(max_length=100)),
                ('terms', models.CharField(max_length=1000)),
                ('return_policy', models.CharField(max_length=1000)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Node')),
            ],
        ),
        migrations.AddField(
            model_name='moderator',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Node'),
        ),
        migrations.AddField(
            model_name='listing',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Store'),
        ),
        migrations.AddField(
            model_name='follower',
            name='followed_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_node', to='browser.Node'),
        ),
        migrations.AddField(
            model_name='follower',
            name='following_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_node', to='browser.Node'),
        ),
        migrations.AddField(
            model_name='blocked',
            name='blocked_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_node', to='browser.Node'),
        ),
        migrations.AddField(
            model_name='blocked',
            name='blocking_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_node', to='browser.Node'),
        ),
        migrations.AddField(
            model_name='address',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Node'),
        ),
    ]
