# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatars'),
        ),
    ]
