# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_node_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
